server:
  port: 5551
spring:
  application:
    name: ribbon-concumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/,http://localhost:1112/eureka/

#EUREKA-CLIENT:
  #ribbon:
    #NFLoadBalancerClassName: com.netflix.loadbalancer.ZoneAwareLoadBalancer
    #listOfServers: localhost:8001,localhost:8002

ribbon:
  ConnectTimeout: 250
